name: Release

on:
  push:
    tags: [ 'v*.*.*' ]

jobs:
  release:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write
      packages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
      - name: Get latest Go version
        id: gover
        run: echo goversion=$(awk -F':|-' '/^FROM golang/ {print $2}' Dockerfile) >> "$GITHUB_OUTPUT"
      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: "${{ steps.gover.outputs.goversion }}"
          cache: false
      - name: Extract release changelog
        id: version
        run: |
          version=${GITHUB_REF#refs/tags/v*}
          mkdir -p tmp
          sed '/^# '$version'/,/^# /!d;//d;/^\s*$/d' CHANGELOG.md > tmp/release_changelog.md
          echo VERSION=$version >> "$GITHUB_OUTPUT"
      - name: Release
        uses: goreleaser/goreleaser-action@5daf1e915a5f0af01ddbcd89a43b8061ff4f1a89 # v7.2.2
        with:
          distribution: goreleaser
          version: v2.0.1
          args: release --clean --release-notes=tmp/release_changelog.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: ruby/setup-ruby@afeafc3d1ab54a631816aba4c914a0081c12ff2f # v1.310.0
        with:
          ruby-version: 2.7.3
      - name: RubyGem
        id: rubygem
        run: ./rubygem/build.sh
        env:
          VERSION: ${{ steps.version.outputs.version }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Gem Asset
        id: upload-gem-asset
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5 # v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: "https://uploads.github.com/repos/${{ github.repository }}/releases/${{ steps.rubygem.outputs.release_id }}/assets?name=ejson2env-${{ steps.version.outputs.version }}.gem"
          asset_path: "./rubygem/ejson2env-${{ steps.version.outputs.version }}.gem"
          asset_name: "ejson2env-${{ steps.version.outputs.version }}.gem"
          asset_content_type: application/x-tar
      - name: Configure RubyGems credentials
        uses: rubygems/configure-rubygems-credentials@dc5a8d8553e6ee01fc26761a49e99e733d17954a # v2.1.0
      - name: Publish to RubyGems.org
        run: gem push "./rubygem/ejson2env-${VERSION}.gem" --host https://rubygems.org
        env:
          VERSION: ${{ steps.version.outputs.version }}
